### ISSUE TITLE
NPM version out of date

### ISSUE THREAD

**Issue by spbriggs** [MadeinFrance/react-native-share-pdf#18]
**Describe the bug**
The version in the NPM repository is behind this version. I've had to manually copy some of the latest commits into my yarn-installed version to get it to compile

**To Reproduce**

yarn add react-native-share-pdf
Observe that the installed version doesn't have this commit for example https://github.com/MadeinFrance/react-native-share-pdf/commit/b6df0d9f7cc7193ec65d4dd4956d46afb52dd6b9

**Expected behavior**
NPM installs the latest version

**Comment by MadeinFrance** [comment]
updated to 0.0.4
