### ISSUE TITLE
package android.support.v4.content does not exist

### ISSUE THREAD

**Issue by erie-e9** [MadeinFrance/react-native-share-pdf#30]
**Describe the bug**
I just installed this package and get this error: 
Uri outputFileUri = FileProvider.getUriForFile(reactContext, reactContext.getPackageName() + ".provider", file);
                        ^
  symbol:   variable FileProvider
  location: class ShareFile

**Info**

"react": "16.13.1",
"react-native": "0.63.4",
"react-native-share-pdf": "^0.0.6",

**Comment by lucasroca** [comment]
@Eric-Andrade I'm having the same issue. Have you managed to solve it?

**Comment by lucasroca** [comment]
@Eric-Andrade running `jetifier` solved it for me. I added it as an npm postinstall script.

**Comment by sataporn8063** [comment]
same after update android api to level 30 and react-native 0.65

**Comment by MadeinFrance** [comment]
Should be fixed in [v0.0.7](https://www.npmjs.com/package/react-native-share-pdf/v/0.0.7)
