### ISSUE TITLE
This is completely trash module. Does not work at all!

### ISSUE THREAD

**Issue by deenMuhammad** [MadeinFrance/react-native-share-pdf#8]
First of all, android folder does not have build.gradle file, that makes the application stuck in nowhere that it does not run at all. 
I consider this kind of modules to be virus in react-native community

**Comment by MadeinFrance** [comment]
https://github.com/MadeinFrance/react-native-share-pdf/blob/master/android/build.gradle

Feel free to open a PR to improve.

**Comment by JulienMeziere** [comment]
This package works perfectly well.

**Comment by minuitagency** [comment]
yes great package, merci MadeInFrance!
